export const GET_DATA_CHARACTERS = "getDataCharacters"
export const SET_SEARCH = "setSearch"
export const SELECTED_FILTER ="selectedFilter"
export const SUM_NEXT_PAGE = "sumNextPage"
export const ERROR ="error"
export const MAX_PAGES="maxPages"